export const initialState = {
  name: '',
  dateOfBirth: '',
  contact: '',
  email: '',
  education: '',
  address: '',
  pastExperience: '',
  profilePicture: '',
  occupation: '',
  language: '',
  language2: '',
  language3: '',
  referrerName: '',
  referrerContact: '',
  hasCriminalRecord: false,
};
